const oracledb = require('oracledb');
const fs = require('fs');
const path = require('path');

// .env 파싱 및 process.env 설정
const envPath = path.join(__dirname, '..', '.env');
if (fs.existsSync(envPath)) {
  const envConfig = fs.readFileSync(envPath, 'utf8');
  envConfig.split('\n').forEach((line) => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) return;
    const match = trimmed.match(/^([^=]+)=(.*)$/);
    if (match) {
      let value = match[2].trim();
      if (value.startsWith('"') && value.endsWith('"')) value = value.slice(1, -1);
      process.env[match[1].trim()] = value;
    }
  });
}

async function run() {
  let conn;
  try {
    conn = await oracledb.getConnection({
      user: process.env.DB_USER,
      password: process.env.DB_PASSWORD,
      connectString: process.env.DB_CONNECT_STRING,
    });
    console.log('Connected to Oracle DB successfully.');

    // 기존 테이블 확인
    const res = await conn.execute("SELECT table_name FROM user_tables");
    const tables = res.rows.map((r) => r[0]);
    console.log('Existing tables in Oracle DB:', tables);

    const ddlList = [
      {
        name: 'API_COMPANIES',
        sql: `CREATE TABLE API_COMPANIES (
            COMPANY_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            COMPANY_NAME VARCHAR2(100) NOT NULL,
            BUSINESS_NUMBER VARCHAR2(50),
            CLIENT_ID VARCHAR2(100) NOT NULL UNIQUE,
            CLIENT_SECRET VARCHAR2(255) NOT NULL,
            STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
            DAILY_LIMIT NUMBER DEFAULT 10000 NOT NULL,
            CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
        )`,
      },
      {
        name: 'API_COMPANY_TOKENS',
        sql: `CREATE TABLE API_COMPANY_TOKENS (
            TOKEN_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ACCESS_TOKEN VARCHAR2(500) NOT NULL UNIQUE,
            REFRESH_TOKEN VARCHAR2(500) UNIQUE,
            COMPANY_ID NUMBER NOT NULL,
            CLIENT_ID VARCHAR2(100) NOT NULL,
            SCOPE VARCHAR2(200) DEFAULT 'read,write',
            ACCESS_TOKEN_EXPIRES_AT TIMESTAMP NOT NULL,
            IS_REVOKED CHAR(1) DEFAULT 'N' CHECK (IS_REVOKED IN ('Y', 'N')),
            CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            CONSTRAINT FK_COMP_TOKENS_COMP FOREIGN KEY (COMPANY_ID) REFERENCES API_COMPANIES(COMPANY_ID) ON DELETE CASCADE
        )`,
      },
      {
        name: 'API_MOVIES',
        sql: `CREATE TABLE API_MOVIES (
            MOVIE_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            COMPANY_ID NUMBER NOT NULL,
            TITLE VARCHAR2(200) NOT NULL,
            ORIGINAL_TITLE VARCHAR2(200),
            RELEASE_DATE DATE,
            RUNNING_TIME NUMBER,
            PLOT CLOB,
            POSTER_URL VARCHAR2(500),
            CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            CONSTRAINT FK_MOVIES_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES API_COMPANIES(COMPANY_ID) ON DELETE CASCADE
        )`,
      },
      {
        name: 'API_CALL_LOGS',
        sql: `CREATE TABLE API_CALL_LOGS (
            LOG_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            COMPANY_ID NUMBER NOT NULL,
            ENDPOINT VARCHAR2(200) NOT NULL,
            HTTP_METHOD VARCHAR2(10) NOT NULL,
            STATUS_CODE NUMBER NOT NULL,
            IP_ADDRESS VARCHAR2(50),
            CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            CONSTRAINT FK_LOGS_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES API_COMPANIES(COMPANY_ID) ON DELETE CASCADE
        )`,
      },
      {
        name: 'API_TODO',
        sql: `CREATE TABLE API_TODO (
            TODO_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            COMPANY_ID NUMBER NOT NULL,
            TITLE VARCHAR2(500) NOT NULL,
            IS_COMPLETED CHAR(1) DEFAULT 'N' CHECK (IS_COMPLETED IN ('Y', 'N')),
            CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            COMPLETED_AT TIMESTAMP,
            CONSTRAINT FK_TODO_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES API_COMPANIES(COMPANY_ID) ON DELETE CASCADE
        )`,
      },
    ];

    for (const item of ddlList) {
      if (!tables.includes(item.name)) {
        console.log(`[CREATE TABLE] Creating ${item.name}...`);
        await conn.execute(item.sql);
        console.log(`[SUCCESS] ${item.name} created successfully.`);
      } else {
        console.log(`[EXISTS] ${item.name} already exists.`);
      }
    }
  } catch (err) {
    console.error('Database execution error:', err);
  } finally {
    if (conn) {
      await conn.close();
    }
  }
}

run();
